apiVersion: v1
kind: Secret
metadata:
  name: it-portal-secret
  namespace: it-portal
type: Opaque
# Les valeurs sont encodées en base64
# Pour encoder : echo -n "valeur" | base64
# Pour décoder : echo "dmFsZXVy" | base64 -d
#
# MotDePasseFormation123 → encodé ci-dessous
stringData:
  POSTGRES_PASSWORD: "MotDePasseFormation123"
  DATABASE_URL: "postgresql://it_admin:MotDePasseFormation123@db-svc:5432/it_portal"
