# docker-compose.yml -- Module 05 Lab basique
version: "3.9"

services:
  web:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - reseau-app

networks:
  reseau-app:
    driver: bridge
