apiVersion: v1
kind: ConfigMap
metadata:
  name: it-portal-config
  namespace: {{ .Values.namespace }}
data:
  APP_ENV: {{ .Values.app.env | quote }}
  APP_VERSION: {{ .Values.app.version | quote }}
  PORT: {{ .Values.app.port | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.namespace }}
data:
  default.conf: |
    server {
        listen 80;
        location / {
            proxy_pass http://it-portal-app-svc:{{ .Values.app.port }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
