apiVersion: v1
kind: Service
metadata:
  name: it-portal-nginx-svc
  namespace: it-support
spec:
  type: NodePort
  selector:
    app: it-portal-nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
